In [1]:
import torch
import torch.nn as nn
import torchvision
import numpy as np
import torchvision.transforms as transforms

In [3]:
x = torch.tensor(10.0 , requires_grad = True)
w = torch.tensor(5.0 , requires_grad = True)
b = torch.tensor(2.0 , requires_grad = True)

In [4]:
y = w*x + b 

In [5]:
#compute gradient
y.backward()

In [6]:
#compute grad
print(x.grad)
print(w.grad)
print(b.grad)

tensor(5.)
tensor(10.)
tensor(1.)


In [10]:
torch.randn(3).shape

torch.Size([3])

In [11]:
x = torch.randn(10 ,3)

In [12]:
y = torch.randn(10 , 2)

In [13]:
print(x)

tensor([[-0.6120,  0.2920,  0.6790],
        [-0.0259,  0.9472,  0.5120],
        [-0.8103,  0.6171, -1.2129],
        [-0.3795,  0.9391, -0.6970],
        [-1.3107,  0.8368, -0.2377],
        [-0.6422,  1.0913, -0.5095],
        [-1.9373, -0.9677,  0.0349],
        [-0.3308,  0.7391, -0.1819],
        [ 0.2273, -1.7210, -1.0191],
        [ 1.1702,  0.4237, -0.4252]])


In [15]:
#Build fully connected layer
linear = nn.Linear(3,2)
print("linear w: ", linear.weight)
print("linear b: ", linear.bias)

linear w:  Parameter containing:
tensor([[ 0.2465,  0.2989,  0.1212],
        [ 0.4536,  0.2229, -0.0767]], requires_grad=True)
linear b:  Parameter containing:
tensor([0.2326, 0.2448], requires_grad=True)


In [18]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(),lr = 0.01)

In [19]:
pred = linear(x)

In [20]:
print(pred)
print(y)

tensor([[ 0.2513, -0.0198],
        [ 0.5715,  0.4050],
        [ 0.0704,  0.1078],
        [ 0.3354,  0.3355],
        [ 0.1309, -0.1450],
        [ 0.3388,  0.2359],
        [-0.5300, -0.8524],
        [ 0.3500,  0.2735],
        [-0.3493,  0.0424],
        [ 0.5963,  0.9027]], grad_fn=<AddmmBackward0>)
tensor([[ 0.1706,  1.2528],
        [-0.1687,  0.0511],
        [-1.6223,  0.5844],
        [-0.8326,  1.3786],
        [-0.0957, -0.6827],
        [-0.9757, -0.0716],
        [-1.7633, -1.2426],
        [-0.0401, -0.7564],
        [-1.7060, -1.7123],
        [-0.3871, -0.8928]])


In [21]:
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  1.1001617908477783


In [22]:
loss.backward()

In [23]:
print("dl/dw: ", linear.weight.grad)

dl/dw:  tensor([[-0.4084,  0.1667, -0.4986],
        [ 0.2053, -0.2400, -0.2387]])


In [24]:
print("dl/db: ", linear.bias.grad)

dl/db:  tensor([0.9186, 0.3377])


In [25]:
optimizer.step()

In [26]:
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())


loss after 1 step optimization:  1.0846866369247437


In [27]:
loss.backward()

In [28]:
optimizer.step()

In [29]:
pred = linear(x)
loss = criterion(pred, y)
print('loss after 2 step optimization: ', loss.item())


loss after 2 step optimization:  1.0545474290847778


Loading data from numpy

In [30]:
x = np.array([[1,2],[3,4]])

In [31]:
y = torch.from_numpy(x)

In [32]:
print(y)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [33]:
z = y.numpy()
print(z)

[[1 2]
 [3 4]]


Input pipeline

In [35]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ../../data/cifar-10-python.tar.gz to ../../data/


In [38]:
image, label = train_dataset[0]
print (image.size())
print (label)


torch.Size([3, 32, 32])
6


In [39]:
# Data loader (this provides queues and threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64, 
                                           shuffle=True)

In [40]:
# When iteration starts, queue and thread start to load data from files.
data_iter = iter(train_loader)

# Mini-batch images and labels.
images, labels = data_iter.next()

In [ ]:
# Actual usage of the data loader is as below.
for images, labels in train_loader:
    # Training code should be written here.
    
